// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkoqkqhjfshrkcswttpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrb3FrcWhqZnNocmtjc3d0dHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjMwMjMsImV4cCI6MjA3NjE5OTAyM30.dv-1w8nO2GWSapLa0O-vyY-YqLsYEaFVoF36kl8_dro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});